### ISSUE TITLE
Memory cycle in password callback and in ArchiveRead open callback

### ISSUE THREAD

**Issue by plicease** [uperl/Archive-Libarchive#36]
When I was debugging something else I realized there is a memory cycle in the passphrase callback option.  Setting the passphrase without a callback should be fine.

**Comment by ashleynewson** [comment]
This issue isn't specific to the passphrase callback. It also happens with callback-based open.

When using Archive::Libarchive::ArchiveRead's callback-based open, it creates a closure which captures (by reference) `$self` (the ArchiveRead object).

https://github.com/uperl/Archive-Libarchive/blob/6354a8fcdfb8f94ad6212d0817e672edc2fdd26f/lib/Archive/Libarchive/ArchiveRead.pm#L165-L172

`$self` then saves a reference to the closure in `$self->{keep}`, so that it does not get destroyed whilst a reference exists in C code.

https://github.com/uperl/Archive-Libarchive/blob/6354a8fcdfb8f94ad6212d0817e672edc2fdd26f/lib/Archive/Libarchive/ArchiveRead.pm#L182

`$self->{keep}` is never cleared within the module's code. As such, there exists a circular reference that cannot be broken without tampering with the ArchiveRead's internal `keep` arrayref from user code.

The closure could either not reference the entirety of `$self`, capturing specific variables or refs to pre-initialised variables, or use some form of weak reference.

The passphrase closure has a similar problem.

https://github.com/uperl/Archive-Libarchive/blob/6354a8fcdfb8f94ad6212d0817e672edc2fdd26f/lib/Archive/Libarchive/ArchiveRead.pm#L366-L375

**Comment by plicease** [comment]
@ashleynewson thanks for pointing this out.  I've added memory leak tests and fixed all of the leaks that I am aware of in #42
